# Defines the name that appears in the GitHub Actions tab
name: DeployDiscordBot

# Specifies when this workflow should run
on:
  push:
    branches: [master] # Triggers only when code is pushed to the master branch

# The actual jobs to run
jobs:
  deploy: # Name of the job
    runs-on: ubuntu-latest # Uses the latest Ubuntu runner provided by GitHub

    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v2 # This action checks out your repository code

      # Step 2: Set up SSH for deployment
      - name: Add SSH key
        run: |
          # Create .ssh directory if it doesn't exist
          mkdir -p ~/.ssh

          # Save the private key from GitHub secrets to a file
          # The secret SSH_PRIVATE_KEY must be added to the repository settings
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          # Set correct permissions for the SSH key (required by SSH)
          chmod 600 ~/.ssh/id_rsa

          # Add the host to known_hosts to prevent SSH verification prompts
          # secrets.HOST is your server's IP address
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: test connection
        run: |
          # test connection works
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "pwd"

      # Create directory if it doesn't exist
      - name: Create bot directory
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "mkdir -p ~/bots/${{ github.repository_owner }}"

      - name: Copy files to the server
        run: |
          scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:~/bots/${{ github.repository_owner }}/

      - name: export DISCORD_TOKEN
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "export DISCORD_TOKEN='${{ secrets.DISCORD_TOKEN }}'"

      - name: get env variables
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "cp credentials/.env bots/SkatAI/"

      - name: Build and run with docker compose -d --build
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "cd ~/bots/${{ github.repository_owner }} && docker compose up -d --build"
